---
title: "Ecuador plant richness analysis"
authors: "Hazel J. Anderson"
data input: "Ecuador_BIEN_plant_cleaned.csv"
data output: ""
date: "2022-11-30"
output: html_document
---

# Set file paths
```{r}
data_path <- file.path('G:/My Drive/IBIO 870/Final project/data/L1')
output_path <- file.path('G:/My Drive/IBIO 870/Final project/data/L2')
```

# Load required packages
```{r}
library(sp)
library(sf)
library(dplyr)
library(ggplot2)
library(scico)
library(rnaturalearth)
library(purrr)
library(ggsn)
library(fasterize)
library(raster)
```

# Load cleaned BIEN data
```{r}
Ecuador_plants <- read.csv(file.path(data_path,"Ecuador_BIEN_plant_cleaned.csv"))
```

# Calculate richness
Modified from https://github.com/bioXgeo/neotropical_plants/blob/master/archive/EcuadorPlantsStackedSpeciesMaps.Rmd
## Load in world map
```{r}
worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")
# country subset. In this case we are removing the Galapagos by defining the bounding box around the Ecuador polygon.
CRpoly <- worldMap %>% filter(sovereignt == "Ecuador")
ecuador_shp <-st_crop(CRpoly, c(xmin=-84, xmax=-75.24961, ymin=-4.990625, ymax=1.455371))
# trim the map to appropriate study area. This zooms out of Ecuador, which will be easier for visualization down the line.
limsCR <- st_buffer(ecuador_shp, dist = 1) %>% st_bbox()
# countries
divpolPlot <-
ggplot() +
geom_sf(data = ecuador_shp) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#ffffff"),
panel.background = element_rect(fill = "#ffffff"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
divpolPlot
```

## Plot hulls
```{r}
hullsPlot <-
ggplot() +
geom_sf(data = ecuador_shp) +
geom_sf(data = Ecuador_plants, aes(fill = species), alpha = 0.7) +
scale_fill_scico_d(palette = "davos", direction = -1, end = 0.9, guide = FALSE) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#FFFFFF"),
panel.background = element_rect(fill = "#FFFFFF"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
hullsPlot
```

## Define a grid
```{r}
CRGrid <- ecuador_shp %>%
st_make_grid(cellsize = 0.2) %>%
st_intersection(ecuador_shp) %>%
st_cast("MULTIPOLYGON") %>%
st_sf() %>%
mutate(cellid = row_number())
```

## Richness for convex hulls
```{r}
richness_gridEOO <- CRGrid %>%
st_join(Ecuador_plants) %>%
mutate(overlap = ifelse(!is.na(id), 1, 0)) %>%
group_by(cellid) %>%
summarize(num_species = sum(overlap))
```

## Empty grid, more detailed in nature
```{r}
gridPlot <-
ggplot() +
geom_sf(data =ecuador_shp) +
geom_sf(data = CRGrid) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#FFFFFF"),
panel.background = element_rect(fill = "#FFFFFF"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
gridPlot
```

## Richness for convex hulls, more detailed
```{r}
gridRichCR_eoo <-
ggplot(richness_gridEOO) +
geom_sf(data = ecuador_shp, fill = "grey", size = 0.1) +
geom_sf(aes(fill = num_species), color = NA) +
scale_fill_scico(palette = "davos", direction = -1, end = 0.9) +
coord_sf(
xlim = c(limsCR["xmin"], limsCR["xmax"]),
ylim = c(limsCR["ymin"], limsCR["ymax"])
) +
scale_x_continuous(breaks = c(-84)) +
theme(
plot.background = element_rect(fill = "#FFFFFF"),
panel.background = element_rect(fill = "#FFFFFF"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank(),
axis.title.x = element_blank(),
axis.title.y = element_blank()
) + 
scalebar(ecuador_shp, dist = 200, st.dist=.05, st.size=4, height=0.02, transform = TRUE, dist_unit = "km", model = 'WGS84') +
north(ecuador_shp, location="topright", scale=0.15, symbol=3) +
labs(fill = "richness") 
gridRichCR_eoo
```

## Saving richness map
```{r}
ggsave(filename = "Plant richness map Ecuador.png", dpi = 300, device="png")
```

## Convert map into raster
```{r}
# Run fasterize to turn the richness map into a raster 
raster_grid <- fasterize(
  richness_gridEOO,
  for_cov,
  field = "num_species",
  fun = "sum",
  background = NA,
)
#Write the richness raster to a file 
writeRaster(raster_grid, filename="G:/Shared drives/SpaCE_Lab_FRUGIVORIA/analysis/MODIS_data_2019/plant_ric.tif", format="GTiff")
#read in raster
raster_grid <- raster("G:/Shared drives/SpaCE_Lab_FRUGIVORIA/analysis/MODIS_data_2019/plant_ric.tif")
```

