---
title: "Ecuador plant BIEN data"
authors: "Hazel J. Anderson"
data input: "none"
data output: ""
date: "2022-08-17"
output: html_document
---
# Set file paths
```{r}
data_path <- file.path('G:/My Drive/IBIO 870/Final project/data/L0')
output_path <- file.path('G:/My Drive/IBIO 870/Final project/data/L0')
```

# Load required packages
```{r}
library(BIEN)
```


# Get data for Ecuador from BIEN database

```{r}
# occurrence data
Ecuador_BIEN_occ <- BIEN_occurrence_country("Ecuador", all.taxonomy = TRUE, observation.type = TRUE, collection.info = TRUE)
# species list
Ecuador_BIEN_species_list <- BIEN_list_country(country = "Ecuador")
# trait data
Ecuador_BIEN_traits <- BIEN_trait_country("Ecuador", all.taxonomy = TRUE)
```

```{r}
# range maps
species_names <- Ecuador_BIEN_species_list$scrubbed_species_binomial
Ecuador_BIEN_ranges <- BIEN_ranges_species_bulk(species = species_names, directory = output_path, batch_size = 1000, use_parallel = TRUE)
```


# Write data to csv
```{r}
Ecuador_BIEN_occurrence_path <- file.path(output_path,"Ecuador_BIEN_occurrence.csv") 
write.csv(Ecuador_BIEN_occ, file = Ecuador_BIEN_occurrence_path)
Ecuador_BIEN_traits_path <- file.path(output_path, "Ecuador_BIEN_traits.csv")
write.csv(Ecuador_BIEN_traits, file = Ecuador_BIEN_traits_path)
```
