---
title: "Ecuador plant richness analysis"
authors: "Hazel J. Anderson"
data input: "Ecuador_BIEN_plant_cleaned.csv"
data output: ""
date: "2022-11-30"
output: 
  html_document: 
    fig_width: 10
    fig_height: 10
    fig_caption: yes
---

# Set file paths
```{r}
data_path <- file.path('G:/My Drive/IBIO 870/Final project/data/L1')
output_path <- file.path('G:/My Drive/IBIO 870/Final project/data/L2')
```

# Load required packages
```{r}
library(sp)
library(sf)
library(dplyr)
library(ggplot2)
library(scico)
library(rnaturalearth)
library(purrr)
library(ggsn)
library(fasterize)
library(raster)
library(smoothr)
library(sampbias)
```

# Load cleaned BIEN data
```{r}
Ecuador_plants <- read.csv(file.path(data_path,"Ecuador_BIEN_plant_cleaned.csv"))
```

# Calculate richness
Modified from https://github.com/bioXgeo/neotropical_plants/blob/master/archive/EcuadorPlantsStackedSpeciesMaps.Rmd & https://luisdva.github.io/rstats/richness/

## Convert data into sf object
```{r}
Ecuador_plants$species <- Ecuador_plants$Scientific_name

# species and lat long data
Ecuador_plants <- Ecuador_plants %>%
  dplyr::select(species, Longitude, Latitude) %>%
  na.omit()

# convert to sf
Ecuador_plants_sf <- st_as_sf(Ecuador_plants, coords = c("Longitude", "Latitude"), crs = 32617) %>%
  group_by(species) %>%
  summarize()
Ecuador_plants_sf <- st_transform(Ecuador_plants_sf, value = 32617)
```

## Load in world map
```{r}

worldMap <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")
worldMap <- st_transform(worldMap, crs = 32617)
# country subset
ECpoly <- worldMap %>% filter(sovereignt == "Ecuador")
ECpoly <- st_transform(ECpoly, crs = 32617)
# trim the map to appropriate study area.
limsEC <- st_buffer(ECpoly, dist = 0.7) %>% st_bbox()

# neighboring countries
COpoly <- worldMap %>% filter(sovereignt == "Colombia")
COpoly <- st_transform(COpoly, crs = 32617)
PEpoly <- worldMap %>% filter(sovereignt == "Peru")
PEpoly <- st_transform(PEpoly, crs = 32617)


divpolPlot <-
ggplot() +
geom_sf(data = COpoly, color = "white") +
geom_sf(data = PEpoly, color = "white") +
geom_sf(data = ECpoly) +
coord_sf(
xlim = c(limsEC["xmin"], limsEC["xmax"]),
ylim = c(limsEC["ymin"], limsEC["ymax"])
) +
theme(
plot.background = element_rect(fill = "#f1f2f3"),
panel.background = element_rect(fill = "#2F4051"),
panel.grid = element_blank(),
line = element_blank(),
rect = element_blank()
)
divpolPlot
```

## Plot points
```{r}
plantPointsPlot <-
  ggplot() +
  geom_sf(data = COpoly, color = "white") +
  geom_sf(data = PEpoly, color = "white") +
  geom_sf(data = ECpoly) +
  geom_sf(data = Ecuador_plants_sf, pch = 12) +
  coord_sf(
    xlim = c(limsEC["xmin"], limsEC["xmax"]),
    ylim = c(limsEC["ymin"], limsEC["ymax"])
  ) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
plantPointsPlot
```

```{r}
plantPointsPlot <-
  ggplot() +
  geom_sf(data = Ecuador_plants_sf, pch = 21) 
plantPointsPlot
```

## Define a grid
```{r}
ECGrid <- ECpoly %>%
st_make_grid(cellsize = 0.2) %>%
st_intersection(ECpoly) %>%
st_cast("MULTIPOLYGON") %>%
st_sf() %>%
mutate(cellid = row_number())

gridPlot <-
  ggplot() +
  geom_sf(data = neighbors, color = "white") +
  geom_sf(data = ECpoly) +
  geom_sf(data = ECGrid) +
  coord_sf(
    xlim = c(limsEC["xmin"], limsEC["xmax"]),
    ylim = c(limsEC["ymin"], limsEC["ymax"])
  ) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    line = element_blank(),
    rect = element_blank()
  )
gridPlot
```

## Richness 
```{r}
plant_richness_grid <- ECGrid %>%
  st_join(Ecuador_plants_sf) %>%
  mutate(overlap = ifelse(!is.na(species), 1, 0)) %>%
  group_by(cellid) %>%
  summarize(num_species = sum(overlap))

# plot
plantRichEC <-
  ggplot(plant_richness_grid) +
  geom_sf(data = neighbors, color = "white") +
  geom_sf(data = ECpoly, fill = "grey", size = 0.1) +
  geom_sf(aes(fill = num_species), color = NA) +
  scale_fill_scico(palette = "davos", direction = -1, end = 0.9, name = "Plant species richness") +
  coord_sf(
    xlim = c(limsEC["xmin"], limsEC["xmax"]),
    ylim = c(limsEC["ymin"], limsEC["ymax"])
  ) +
  theme(
    plot.background = element_rect(fill = "#f1f2f3"),
    panel.background = element_rect(fill = "#2F4051"),
    panel.grid = element_blank(),
    legend.position = "bottom",
    line = element_blank(),
    rect = element_blank()
  ) + labs(fill = "richness")
plantRichEC
```

## Saving richness map
```{r}
ggsave(filename = "Plant richness map Ecuador.png", dpi = 300, device="png")
```


# Calculate sample bias
```{r}

```

